# ئەمانە بۆ ئەوەیە بزانێت بۆ چ جۆرە ئایفۆنێک دروست دەکرێت
ARCHS = arm64 arm64e
TARGET = iphone:clang:latest:14.5

include $(THEOS)/makefiles/common.mk

# لێرە ناوی تویکەکەت بنووسە
TWEAK_NAME = DayLB_AlanVIP

# لێرە ناوی ئەو فایلانە بنووسە کە کۆدەکەی تێدایە (وەک Tweak.x یان Tweak.xm)
DayLB_AlanVIP_FILES = Tweak.x
DayLB_AlanVIP_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
