name: Build-Alan-VIP
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos and SDKs
        run: |
          export THEOS=/Users/runner/theos
          sudo rm -rf $THEOS
          git clone --recursive https://github.com/theos/theos.git $THEOS
          git clone https://github.com/theos/sdks.git $THEOS/sdks

      - name: Build Project
        run: |
          export THEOS=/Users/runner/theos
          # لێرەدا فەرمانەکە دەڵێت: بگەڕێ بەدوای هەر شوێنێک Makefile لێیە و لەوێوە Build بکە
          find . -name "Makefile" -exec dirname {} \; | xargs -I {} sh -c "cd {} && make FINALPACKAGE=1"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Alan-VIP-Output
          path: |
            packages/*.deb
            **/.theos/obj/*.dylib
            **/*.dylib
