- name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Alan-VIP-Output
          # گەڕان لە هەموو شوێنێک بۆ فایلەکان
          path: |
            ./packages/*.deb
            ./**/*.dylib
            ./.theos/obj/*.dylib
          if-no-files-found: error # ئەگەر نەیدۆزیەوە با هەڵە بدات تا بزانین کێشەکە لە کوێیە
